# Generated by Django 4.1.5 on 2023-01-24 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_topic_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='creator',
        ),
    ]
